# Generated by Django 4.0.3 on 2022-03-13 11:39

import Teatre.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15, validators=[Teatre.validators.PhoneValidator])),
                ('cardNumber', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator('Must be a valid email')])),
                ('NIF', models.CharField(max_length=9, validators=[Teatre.validators.DNIValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genere', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('descripton', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(50)])),
                ('number', models.IntegerField()),
                ('idCinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teatre.cinema')),
            ],
            options={
                'unique_together': {('number', 'idCinema')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(max_length=4)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teatre.client')),
                ('idMovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teatre.movie')),
                ('idRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teatre.room')),
            ],
            options={
                'unique_together': {('date', 'idClient', 'idMovie', 'idRoom')},
            },
        ),
    ]
