# Generated by Django 4.0.3 on 2022-03-19 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teatre', '0003_rename_address_client_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='idClient',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='idMovie',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='idRoom',
            new_name='Room',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('date', 'Client', 'Movie', 'Room')},
        ),
    ]
