# Generated by Django 4.0.2 on 2022-03-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teatre', '0004_rename_idclient_ticket_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
    ]
