# Generated by Django 4.0.3 on 2022-03-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teatre', '0005_rename_adress_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='classification',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
