# Generated by Django 4.0.3 on 2022-04-30 10:04

import Teatre.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teatre', '0006_movie_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15, validators=[Teatre.validators.PhoneValidator])),
                ('DNI', models.CharField(default='', max_length=9, validators=[Teatre.validators.DNIValidator])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
