# Generated by Django 4.0.3 on 2022-04-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teatre', '0007_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
