# Generated by Django 4.0.3 on 2022-05-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teatre', '0008_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCinemaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_movie', models.DateField(verbose_name='date_movie')),
                ('Cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teatre.cinema')),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teatre.movie')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teatre.room')),
            ],
        ),
    ]
