# Generated by Django 4.0.3 on 2022-05-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teatre', '0009_moviecinemaroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecinemaroom',
            name='Cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teatre.cinema'),
        ),
        migrations.AlterField(
            model_name='moviecinemaroom',
            name='Movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teatre.movie'),
        ),
        migrations.AlterField(
            model_name='moviecinemaroom',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teatre.room'),
        ),
        migrations.AlterField(
            model_name='moviecinemaroom',
            name='date_movie',
            field=models.DateField(null=True, verbose_name='date_movie'),
        ),
    ]
